language: python

env:
  global:
    - REPO_DIR=/home/travis/build/zhaw-charts
    - GH_URL=https://kubenow.github.io/helm-charts

install:
  - PATH=`pwd`/linux-amd64/:$PATH
  - sudo apt-get install jq
  - sudo apt-get install curl
 
script: ./test.sh
